--SELECT * FROM film ORDER BY title ASC;
--SELECT * FROM film ORDER BY title DESC;
--SELECT * FROM film WHERE title LIKE 'A%' ORDER BY title ASC, length DESC;
--SELECT * FROM film WHERE title LIKE 'B%' ORDER BY length DESC LIMIT 10;
--SELECT * FROM film WHERE title LIKE 'B%' ORDER BY length DESC OFFSET 6 LIMIT 4;